version: '2'
volumes:
  redis_data:
    external: true
    driver: rancher-nfs
  elasticsearch_data:
    external: true
    driver: rancher-nfs
services:
  letsencrypt:
    image: vxcontrol/rancher-letsencrypt:v1.0.0
    environment:
      API_VERSION: Production
      CERT_NAME: {{ .Stack.Name }}
      DNS_RESOLVERS: 8.8.8.8:53,8.8.4.4:53
      DOMAINS: ${domain_list}
      EMAIL: serviceadmin@artbutler.com
      EULA: 'Yes'
      PROVIDER: HTTP
      PUBLIC_KEY_TYPE: RSA-4096
      RENEWAL_PERIOD_DAYS: '30'
      RENEWAL_TIME: '3'
      RUN_ONCE: 'false'
    volumes:
    - /var/lib/rancher:/var/lib/rancher
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  vue:
    image: 438817670771.dkr.ecr.eu-central-1.amazonaws.com/abnext/frontend:0.0.5
    environment:
      VUE_APP_ENV_NAME: "production"
      VUE_APP_I18N_LOCALE: "en"
      VUE_APP_I18N_FALLBACK_LOCALE: "en"
      VUE_APP_KEYCLOAK_REALM: ${keycloak_realm}
      VUE_APP_KEYCLOAK_URL: "${keycloak_base_url}/auth"
      VUE_APP_KEYCLOAK_CLIENT_ID: ${keycloak_client_id}
      VUE_APP_NODE_ENV: "production"
      VUE_APP_GRAPHQL_HTTP: "https://${app_url}/graphql"
      VUE_APP_REST: "https://${app_url}"
  laravel:
    image: 438817670771.dkr.ecr.eu-central-1.amazonaws.com/abnext/backend:0.0.6
    environment:
      APP_ENV: ${app_env}
      APP_KEY: ${app_key}
      APP_URL: ${app_url}
      LOG_CHANNEL: ${log_channel}
      LOG_LEVEL: notice
      DB_HOST: ${db_host}
      DB_PORT: ${db_port}
      DB_CONNECTION: tenant
      DB_DATABASE: ${db_database}
      DB_USERNAME: ${db_username}
      DB_PASSWORD: ${db_password}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${redis_password}
      REDIS_PORT: 6379
      MAIL_MAILER: smtp
      MAIL_HOST: ${smtp_host}
      MAIL_PORT: ${smtp_port}
      MAIL_USERNAME: ${smtp_username}
      MAIL_PASSWORD: ${smtp_password}
      MAIL_ENCRYPTION: ${smtp_encryption}
      MAIL_FROM_ADDRESS: ${smtp_from_address}
      MAIL_FROM_NAME: ${smtp_from_name}
      AWS_ACCESS_KEY_ID: ${aws_access_key_id}
      AWS_SECRET_ACCESS_KEY: ${aws_secret_access_key}
      AWS_DEFAULT_REGION: ${aws_default_region}
      AWS_BUCKET: ${aws_bucket}
      KEYCLOAK_REALM_PUBLIC_KEY: ${keycloak_realm_public_key}
      KEYCLOAK_ALLOWED_RESOURCES: ${keycloak_allowed_resources}
      KEYCLOAK_BASE_URL: ${keycloak_base_url}
      KEYCLOAK_REALM: ${keycloak_realm}
      KEYCLOAK_CLIENT_ID: ${keycloak_client_id}
      KEYCLOAK_CLIENT_SECRET: ${keycloak_client_secret}
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      REDIS_PASSWORD: ${redis_password}
    volumes:
      - 'redis_data:/bitnami/redis/data'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
