version: '2'

services:
  gotenberg:
    image: gotenberg/gotenberg:7
    command: gotenberg --api-read-timeout=${api_read_timeout} --api-process-timeout=${api_process_timeout} --api-write-timeout=${api_write_timeout}
